###################################################################
# About the weight:
#
#     1: "About" section
#   2~9: Other future sections we'd like to add
# 10~89: Garden sections
#    90: "Vlog" section
#  100~: Subsections
#
#	Note that we reserved the numbers 2~9 in case we'd like to 
# add new sections above the gardens sections.
#
# Also, for subsections' weight, multiply by a 100. For example,
# Prairie Restoration Garden has a weight of 20. For projects
# on this garden, the weight range would be 200~299. For instance,
# First project of the garden would have a weight of 200.
###################################################################

[[docs]]
  name = "About"
  identifier = "about"
	weight = 1
  url = "/docs/about/"

[[docs]]
  name = "Prairie Restoration Garden"
  identifier = "prairie-restoration-garden"
	weight = 20
  url = "/docs/prairie-restoration-garden/"

[[docs]]
  name = "The Beehives"
  identifier = "the-beehives"
	weight = 30
  url = "/docs/the-beehives/"

[[docs]]
  name = "Campus Orchard"
  identifier = "campus-orchard"
	weight = 40
  url = "/docs/campus-orchard/"

[[docs]]
  name = "Organic Vegetable Garden"
  identifier = "organic-vegetable-garden"
	weight = 50
  url = "/docs/organic-vegetable-garden/"

[[docs]]
  name = "Meditative Labryinth"
  identifier = "meditative-labryinth"
	weight = 60
  url = "/docs/meditative-labryinth/"

[[docs]]
  name = "The Plot"
  identifier = "the-plot"
	weight = 70
  url = "/docs/the-plot/"

[[docs]]
  name = "Vlog"
  identifier = "vlog"
	weight = 90
  url = "/docs/vlog/"






# [[docs]]
#   name = "Prologue"
#   weight = 99
#   identifier = "prologue"
#   url = "/docs/prologue/"

# [[docs]]
#   name = "Help"
#   weight = 99
#   identifier = "help"
#   url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

# [[guide]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/guide/lorem/"

# [[tutorial]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/tutorial/lorem/"

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "Documentation"
  url = "/docs/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

[[main]]
  name = "Vlog"
  url = "/docs/vlog"
  weight = 20

[[main]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/docs/about/why/"

[[main]]
  name = "Why?"
  weight = 40
  identifier = "why"
  url = "/docs/about/why/"
  parent = "about"

[[main]]
  name = "Who are we?"
  weight = 50
  identifier = "tutorial"
  url = "/docs/about/who-are-we/"
  parent = "about"

[[main]]
  name = "Location"
  weight = 60
  identifier = "Location"
  url = "/docs/about/location/"
  parent = "about"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/Augie-Environmental-Studies/gardens"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Instagram"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-instagram\"><rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5\" ry=\"5\"></rect><path d=\"M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z\"></path><line x1=\"17.5\" y1=\"6.5\" x2=\"17.51\" y2=\"6.5\"></line></svg>"
  url = "https://www.instagram.com/augustana_garden/"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
