# Taken from:
# https://getdoks.org/docs/how-to/hosting/deployment/

# Deploy your Hyas site to GitHub Pages

name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./src/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Check for linting errors
        run: npm test
        working-directory: ./src

      - name: Build production website
        run: npm run build
        working-directory: ./src

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
